version: '3.2'
services:
  api:
    build:
      dockerfile: Dockerfile-api
      context: .
    ports:
      - 8081:8080
  web:
    build:
      dockerfile: Dockerfile-web
      context: .
    ports:
      - 8082:8080